name: rails
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:alpine
        ports: [ "6379:6379" ]
        options: --entrypoint redis-server

    steps:
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: "Checkout repository"
        uses: actions/checkout@v1

      - name: "Install Ruby version specified in `.ruby-version`"
        uses: eregon/use-ruby-action@master

      - name: "Setup caching for Ruby gems cache"
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: "Bundle install"
        run: |
          gem install bundler && bundle update --bundler && bundle -v
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Bundle outdated"
        continue-on-error: true
        run: bundle outdated

      - name: "Rails test"
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:setup --trace
          bundle exec rails test
          bundle exec rails zeitwerk:check
